Thursday Feb 27th Textir & K means - Nelson Auner
========================================================

```{r init,echo=TRUE,comment="",cache=TRUE,message=FALSE}
## textir & k-means ##
# borrowing heavily from documentation: http://cran.r-project.org/web/packages/textir/textir.pdf
library(textir);data(we8there);cl <- NULL
fits <- mnlm(cl, we8thereRatings[,'Overall',drop=FALSE],we8thereCounts, bins=5, gamma=1, nlambda=10); B <- coef(fits)
# do MNIR projection onto factors
z <- srproj(B,we8thereCounts)
## fit a fwd model to the factors
fwd <- lm(we8thereRatings$Overall ~ z)
head(z)
```

Understanding m: total number of tracked utterances. Linear effect?

```{r kmeans,echo=TRUE,comment="",cache=TRUE,message=FALSE}
#### k-means ##

#quickly scale data
normalize<- function(x) {
return(  
	apply(
		t(apply(t(x),2,FUN=function(x) {x/sum(x)})),
		2,FUN=function(x) {x/sd(x)})
	)}
#how to select # of clusters? I know to be five...
ptm <- proc.time()
km5 <- kmeans(normalize(we8thereCounts),5)
proc.time() - ptm
```

Some more investigative work on how the centers of the means are, since we can't see them:

```{r hdkmtable,echo=TRUE,comment="",cache=TRUE,message=FALSE}
hdkmtable <- function(kmobj,y)  {
  n_y <- length(yu <- as.integer(levels(factor(y))))
	n_km <- length(kmobj$size)
	res<-data.frame(matrix(rep(NA,n_y*(2*n_y)),nrow=n_y))
	names(res) <-c("mean.y","sd.y",paste("cos",2:n_km),paste("dist",2:n_km))
	for (i in 1:n_km) {
		temp.y <- y[kmobj$cluster==i]
		res[i,1:2] <- c(mean(temp.y),sd(temp.y)) 
		if(i == n_km){break()}
		for (j in (i+1):n_km) {
		res[i,(1+j)] <- acos(cor(kmobj$centers[i,],kmobj$centers[j,]))
		res[i,(j+n_km)] <- sqrt(sum((kmobj$centers[i,]-kmobj$centers[j,])^2))
		}
	}
  res$Freq = table(kmobj$cluster)
	return(res)
}

(table5 <- hdkmtable(km5,we8thereRatings$Overall))
```


Nelson's Notes:
- Next Steps? 
- Balancing this vs. pygamlr. 