K means on normalized vs. non-normalized data:
================================================

First, a simple contrived example from 2-gaussian mixture:
```{r,comment=""}
#make reproducible
set.seed(100)
# create mixture:
x <- rbind(matrix(rnorm(10, mean=4,sd = 1), ncol = 2),
           matrix(rnorm(10, mean = 10, sd = 1), ncol = 2))
colnames(x) <- c("x", "y")
cl <- kmeans(x, 2)
plot(x, col = cl$cluster,main="k means on a 2-normal mixture")
points(cl$centers, col = 1:2, pch = 8, cex = 2)
```

Now, we normalize the same data and view quite different results:
```{r,comment=""}
#A normalize function:
normalize<- function(x) {
return(  
	apply(
		t(apply(t(x),2,FUN=function(x) {x/sum(x)})),
		2,FUN=function(x) {x/sd(x)})
	)}

#And now k means on normalized data:
cl2 <- kmeans(normalize(x), 2)
plot(normalize(x), col = cl2$cluster,main="k means on normalized data")
points(cl2$centers, col = 1:2, pch = 8, cex = 2)
```

Why does this happen? Observe what happens to x when we normalize:

```{r,comment=""}
#original data:
x
#deviding by row sum (document frequency):
t(apply(t(x),2,FUN=function(x) {x/sum(x)}))
#and now devide by std of column (standardize term variance):
normalize(x)
plot(normalize(x), col = cl2$cluster,main="k means on normalized data")
```
And we see that the standardized data is not clustered correctly:
```{r,comment=""}
cl$cluster
cl2$cluster
```



